# Generated by Django 3.2.6 on 2021-09-26 16:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210920_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 28, 16, 44, 6, 34119, tzinfo=utc)),
        ),
    ]
